---

- name: Adding Zookeeper ID File | {{ zookeeperDataDir }}/myid
  ansible.builtin.template:
    dest: "{{ zookeeperDataDir }}/myid"
    src: myid
  tags: zookeeper-myid

- name: Creating zookeeper configurations
  ansible.builtin.include_role:
    name: ../roles/zookeeper-configure
    tasks_from: dynamicConfigs.yml
  vars:
    zookeeperConfigFile: "{{ item }}"
  loop:
    - zoo.cfg
    - log4j.properties
    - java.env
  tags: zookeeper-config