---
- hosts: clusterNodes
  gather_facts: true
  become: true
  roles:
    - {role: '../roles/test', tags: 'test'}
    - {role: '../roles/kafka-common', tags: 'kafka-common'}
    - {role: '../roles/kafka-install', tags: 'kafka-install'}
    - {role: '../roles/kafka-configure', tags: 'kafka-configure'}
    - {role: '../roles/kafka-crons', tags: 'kafka-crons'}
    - {role: '../roles/kafka-service', tags: 'kafka-service'}
    - {role: '../roles/kafka-portCheck', tags: 'kafka-portCheck'}

- hosts: clusterNodes
  gather_facts: false
  serial: 1
  tasks:
    - name: starting all nodes
      ansible.builtin.import_role:
        name: ../roles/kafka-serviceState
      vars:
        serviceName: kafka
        serviceState: started

    - name: kafka Port Status
      ansible.builtin.include_role:
        name: ../roles/kafka-portCheck
      vars:
        portNumber: "{{ item }}"
        portStatus: started
      loop:
        - "{{ kafkaPort }}"
        - "{{ kafkaJmxPort }}"