---
- hosts: clusterNodes
  gather_facts: true
  become: true
  roles:
    - ../roles/kafka-common
    - ../roles/kafka-install
    - ../roles/kafka-configure
    - ../roles/kafka-crons
    - ../roles/kafka-service
    - ../roles/kafka-portCheck


- hosts: clusterNodes
  gather_facts: false
  serial: 1
  tasks:
    - name: starting all nodes
      ansible.builtin.import_role:
        name: ../roles/kafka-serviceState
      vars:
        serviceName: kafka
        serviceState: started

    - name: kafka Port Status
      ansible.builtin.include_role:
        name: ../roles/kafka-portCheck
      vars:
        portNumber: "{{ item }}"
        portStatus: started
      loop:
        - "{{ kafkaPort }}"
        - "{{ kafkaJmxPort }}"