---

- hosts: clusterNodes
  gather_facts: true
  become: true
  
  pre_tasks:
    - name: Including system upgrade role
      ansible.builtin.import_role:
        name: ../roles/zookeeper-systemUpgrade
      when: systemUpgradeRequired

    - name: Including java role
      ansible.builtin.import_role:
        name: ../roles/java

  roles:
  - {role: '../roles/test', tags: 'test'}
  - {role: '../roles/zookeeper-common', tags: 'zookeeper-common'}
  - {role: '../roles/zookeeper-install', tags: 'zookeeper-install'}
  - {role: '../roles/zookeeper-configure', tags: 'zookeeper-configure'}
  - {role: '../roles/zookeeper-service', tags: 'zookeeper-service'}

- hosts: clusterNodes
  gather_facts: false
  become: true
  serial: 1
  tasks:
    - name: Starting all nodes
      ansible.builtin.import_role:
        name: ../roles/zookeeper-serviceState
      vars:
        serviceName: zookeeper
        serviceState: started

    - name: zookeeper Port Status
      ansible.builtin.include_role:
        name: ../roles/zookeeper-portCheck
      vars:
        PortNumber: "{{ item }}"
        PortStatus: started
      loop:
        - "{{ zookeeperClientPort }}"
